spring.application.name=payment-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5435/payment_db
spring.datasource.username=payment_user
spring.datasource.password=payment_password

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true